# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField(default=0)),
                ('chapter_name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='Exercise_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=40)),
                ('headline', models.CharField(max_length=30)),
                ('explanation', models.TextField(max_length=150)),
                ('easy_question', models.TextField(default='')),
                ('easy_answer', models.CharField(default='', max_length=30)),
                ('easy_points', models.IntegerField(default=0)),
                ('medium_question', models.TextField(default='')),
                ('medium_answer', models.CharField(default='', max_length=30)),
                ('medium_points', models.IntegerField(default=0)),
                ('hard_question', models.TextField(default='')),
                ('hard_answer', models.CharField(default='', max_length=30)),
                ('hard_points', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=30)),
                ('professor_firstname', models.CharField(max_length=30)),
                ('professor_lastname', models.CharField(max_length=30)),
                ('professor_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.IntegerField(default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set([('subject', 'chapter_number')]),
        ),
    ]
