# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_page',
            name='easy_answer',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='exercise_page',
            name='easy_question',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='exercise_page',
            name='hard_answer',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='exercise_page',
            name='hard_question',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='exercise_page',
            name='medium_answer',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='exercise_page',
            name='medium_question',
            field=models.TextField(default=''),
        ),
    ]
