# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170216_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField()),
                ('headline', models.CharField(max_length=30)),
                ('explanation', models.CharField(max_length=30)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Theme')),
            ],
        ),
    ]
