# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170226_1833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theme',
            new_name='Chapter',
        ),
    ]
